language: groovy
jdk: oraclejdk7
env:
  global:
  - secure: LV2qyNQyknXhmkFomHwxKdOp0ky9piAkeJdr57+rnLXuhQ40tpevYE80IHrkDO1jpScB7rL7HRRNQTBGx9bldm3wfI33TDofyTbREdsNq0ssXQ0FM7zF7dzFuMHcwCSd1NZwWBm6Hwz3vCWY6WhOjfMHTEXJCgLPvz5h2i22F5g=
  - secure: FJPwFSbuU6o6Qhl74ktWs0VYPh3brDiqR53ab7H3brQB8DGhg9k0e9yCTC38OuxF/lEMmqIOaS0bbFmiBHzj0xge+mlIvhBm80F5VdOlwfQEQPZb+PTaKGhUPi5xu7u4QCqZz/riFlPLygLDwEN1J8E5M2th/MPj2ZyYsFE/FAA=
  - secure: a4ApfREP+8pVWXrVCGtS+4BkgeX72h6znHiIqDFR2Oy3XNLTJR8Vv50OuPth126hwjOKyyG9Pee4ArjPUkzhZhkDUZg/1UlV0GYSWvGLZ8m9c4KxoiMA/BAchot9M1oMAGnBSSmvQYzqMMVCfKjVJ5l97FU/g2zf795BrQamXeA=
  - secure: bRUFZm58qSFA4neQm6CkEbAIlDwuHthmJT1lwlWaXs0er+YGXuyvfQ3hLD96jws2F+7H79fsnnGxh74IJsIGZUEKbX1aK3BVfrSaQK0IE0RFzXMshObV/CbcjVDd5HtVSiDl3jummiG2KfyaVFnh0FJjqws3gj9tRQETdqIuJwI=
install: true
script: ./gradlew ci -Dgradle.publish.key=${GRADLE_PUBLISH_KEY} -Dgradle.publish.secret=${GRADLE_PUBLISH_SECRET}
sudo: false
